return {
  VUE_LS = 'vue_ls',
  JSONLS = 'jsonls',
  PYRIGHT = 'pyright',
  RUST_ANALYZER = 'rust_analyzer',
  HTML = 'html',
  CSSLS = 'cssls',
  MARKSMAN = 'marksman',
  TAILWINDCSS = 'tailwindcss',
  GOPLS = 'gopls',
  INTELEPHENSE = 'intelephense',
  TS_LS = 'ts_ls',
  LUA_LS = 'lua_ls',
  SOURCEKIT = 'sourcekit',
  CLANGD = 'clangd',
  KULALA_LS = 'kulala_ls',
  NIX_LS = 'nil_ls',
  PROTOBUF_LS = 'protobuf-language-server',
}
